#!/bin/bash

cd /winattacklab/

echo "=========================="
echo "running the script /opt/scripts/destroy on the server"
echo "=========================="


for i in {1..5}; do 
	echo "`date`: destroy $i of 5"
	sleep 1
done

echo "=========================="

echo "pwd: `pwd`"

